(** See {{:http://www.rapidtables.com/web/color/html-color-codes.htm}this color table}. All colors here have alpha value 255 (opaque). *)

val maroon : int * int * int * int
val brown : int * int * int * int
val sienna : int * int * int * int
val saddlebrown : int * int * int * int
val chocolate : int * int * int * int
val peru : int * int * int * int
val goldenrod : int * int * int * int
val sandybrown : int * int * int * int
val rosybrown : int * int * int * int
val tan : int * int * int * int
val burlywood : int * int * int * int
val wheat : int * int * int * int
val navajowhite : int * int * int * int
val bisque : int * int * int * int
val blanchedalmond : int * int * int * int
val cornsilk : int * int * int * int
val black : int * int * int * int
val darkslategray : int * int * int * int
val slategray : int * int * int * int
val lightslategray : int * int * int * int
val dimgray : int * int * int * int
val gray : int * int * int * int
val darkgray : int * int * int * int
val silver : int * int * int * int
val lightgray : int * int * int * int
val gainsboro : int * int * int * int
val mistyrose : int * int * int * int
val lavenderblush : int * int * int * int
val linen : int * int * int * int
val antiquewhite : int * int * int * int
val ivory : int * int * int * int
val floralwhite : int * int * int * int
val oldlace : int * int * int * int
val beige : int * int * int * int
val seashell : int * int * int * int
val whitesmoke : int * int * int * int
val ghostwhite : int * int * int * int
val aliceblue : int * int * int * int
val azure : int * int * int * int
val mintcream : int * int * int * int
val honeydew : int * int * int * int
val snow : int * int * int * int
val white : int * int * int * int
val mediumvioletred : int * int * int * int
val palevioletred : int * int * int * int
val deeppink : int * int * int * int
val hotpink : int * int * int * int
val lightpink : int * int * int * int
val pink : int * int * int * int
val indigo : int * int * int * int
val purple : int * int * int * int
val darkmagenta : int * int * int * int
val darkorchid : int * int * int * int
val darkviolet : int * int * int * int
val blueviolet : int * int * int * int
val mediumpurple : int * int * int * int
val mediumorchid : int * int * int * int
val magenta : int * int * int * int
val fuchsia : int * int * int * int
val orchid : int * int * int * int
val violet : int * int * int * int
val plum : int * int * int * int
val thistle : int * int * int * int
val lavender : int * int * int * int
val darkslateblue : int * int * int * int
val slateblue : int * int * int * int
val mediumslateblue : int * int * int * int
val midnightblue : int * int * int * int
val navy : int * int * int * int
val darkblue : int * int * int * int
val mediumblue : int * int * int * int
val blue : int * int * int * int
val royalblue : int * int * int * int
val steelblue : int * int * int * int
val cornflowerblue : int * int * int * int
val dodgerblue : int * int * int * int
val lightsteelblue : int * int * int * int
val deepskyblue : int * int * int * int
val skyblue : int * int * int * int
val lightskyblue : int * int * int * int
val lightblue : int * int * int * int
val powderblue : int * int * int * int
val teal : int * int * int * int
val darkcyan : int * int * int * int
val cadetblue : int * int * int * int
val lightseagreen : int * int * int * int
val darkturquoise : int * int * int * int
val mediumturquoise : int * int * int * int
val turquoise : int * int * int * int
val paleturquoise : int * int * int * int
val mediumaquamarine : int * int * int * int
val aquamarine : int * int * int * int
val aqua : int * int * int * int
val cyan : int * int * int * int
val lightcyan : int * int * int * int
val olivedrab : int * int * int * int
val darkolivegreen : int * int * int * int
val olive : int * int * int * int
val seagreen : int * int * int * int
val mediumseagreen : int * int * int * int
val darkseagreen : int * int * int * int
val palegreen : int * int * int * int
val lightgreen : int * int * int * int
val mediumspringgreen : int * int * int * int
val springgreen : int * int * int * int
val yellowgreen : int * int * int * int
val greenyellow : int * int * int * int
val darkgreen : int * int * int * int
val green : int * int * int * int
val forestgreen : int * int * int * int
val lime : int * int * int * int
val limegreen : int * int * int * int
val chartreuse : int * int * int * int
val lawngreen : int * int * int * int
val yellow : int * int * int * int
val darkkhaki : int * int * int * int
val khaki : int * int * int * int
val palegoldenrod : int * int * int * int
val peachpuff : int * int * int * int
val moccasin : int * int * int * int
val papayawhip : int * int * int * int
val lightgoldenrodyellow : int * int * int * int
val lemonchiffon : int * int * int * int
val lightyellow : int * int * int * int
val darkorange : int * int * int * int
val orange : int * int * int * int
val gold : int * int * int * int
val orangered : int * int * int * int
val tomato : int * int * int * int
val coral : int * int * int * int
val darkred : int * int * int * int
val red : int * int * int * int
val firebrick : int * int * int * int
val crimson : int * int * int * int
val indianred : int * int * int * int
val lightcoral : int * int * int * int
val darksalmon : int * int * int * int
val salmon : int * int * int * int
val lightsalmon : int * int * int * int
